### ISSUE TITLE
[Content] Engine news for May

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#10]
**Done**

* Minetest has surpassed 10k commits
* 5.5.1 release ([Changelog](https://dev.minetest.net/Changelog#5.5.0_.E2.86.92_5.5.1))
* Async env updates?
* Performance updates by sfan5
* Content/Select mods fixes.
* Automatic benchmarks
* [Avoid rendering invisible faces of simple nodeboxes](https://github.com/minetest/minetest/commit/cc56ebd90db3858313a9e597a89c5db8fec3b617)

**Upcoming**

* https://github.com/minetest/minetest/pull/12284
* Things in https://github.com/minetest/minetest/milestone/19

**Comment by rubenwardy** [comment]
Updated

**Comment by Zughy** [comment]
* <1000 issues and <100 PRs after a long time
* 5.5.2 coming up and 5.6.0 expected for July
* Android/MacOS being exhumed?
