### ISSUE TITLE
[Content]: 1977 Trans Am added to Automobiles Modpack

### ISSUE THREAD

**Issue by APercy** [minetest/blog#102]
### Blog Section

Mods News

### Please enter your content.

![screenshot_20230429_220540](https://user-images.githubusercontent.com/3141919/235371535-91305e78-317c-4a47-8251-aff61d05797a.jpg)

New car added to automobiles pck, a little tribute to Burth Reynolds.

### Add relevant details

This vehicle introduces an automatic transmission with 2 velocities, but transparent for the player, so the car can be drove on slow roads too.

**Comment by MisterE123** [comment]
Added, thank you!
FYI, we decided not to include a specific Burth Reynolds reference to be sure to maintain a high standard of propriety.

**Comment by APercy** [comment]
okay!
