### ISSUE TITLE
[Content]: X Farming updates

### ISSUE THREAD

**Issue by JurajVajda** [minetest/blog#104]
### Blog Section

Mods News

X Farming added lot of new items to make farming more enjoyable.

Bees for farming honey. Adds new eatable honey as well as new blocks.
Bees are non-entity "mobs" therefore very performant and server friendly.
Video bees: https://youtu.be/rrV4OJ3-IWQ 

Candles - can be coloured with dyes. Four different variations of candles based on players interaction and how many candles will place on the same place. This will affect the light level also.

Stove - BBQ like stove on which you can place up to 6 (cookable) items. This acts like furnace but doesnt require fuel and player can cook multiple items at the same time (limited to 6 items).
Video with (new) rice farm and stove: https://youtu.be/x3cS5REtyjw

Shareable food - food can be placed in the World and anyone wielding bowl can take a portion of that food what opens possibility to nice feasts.
Video shareable foods: https://youtu.be/hpEI5yiTHQE

X Farming has no mandatory dependencies anymore, works with Mineclone and since it doesnt require any dependencies anymore the possibility to support (if not already) with any game is trivial.
Video MCL support: https://youtu.be/KcZGKMjlWOE

More additions:
- ropes
- pillow block (like wool)
- farming rice - screenshot showing rice generating in the World from where you can get seeds
![screenshot_20230426_165628_1920](https://user-images.githubusercontent.com/5089392/235984612-909614bf-9339-4869-8c84-14a058207d76.png)

### Add relevant details

X Farming mod (with screenshots): https://content.minetest.net/packages/SaKeL/x_farming/

**Comment by MisterE123** [comment]
Whew, this was a big one. Added, thanks!
