### ISSUE TITLE
[Content/April]: Minetest presented at the JdLE 2023

### ISSUE THREAD

**Issue by Lemente** [minetest/blog#105]
### Blog Section

Education

### Please enter your content.

![Minetest_JdLE2023](https://user-images.githubusercontent.com/27686967/236218422-f9349fdc-8842-4ae6-a93f-032e8276f661.jpg)

Thomate and Lemente, who use Minetest to host various types of workshops, as well as Riwad Salim and Vincent Puig from the IRI Foundation, who work on the [UNEJ project](https://tac93.fr/capacitation/unej), were invited to present how to "develop an educative and contributive digital common with the Minetest platform" at the French "Journée du Libre Éducatif", an event dedicated to FOSS in education (full program of the event [here](https://journee-du-libre-educatif.forge.aeif.fr/programme/#apres-midi)).
The main goal was to present the possibilities of Minetest and the benefits of FOSS in Education, with projects such as [Minestory](http://minetest.wp.ac-dijon.fr/minestory-frise-immersive-de-sites-du-patrimoine-architectural/), [Minetest Classroom](https://eml.ubc.ca/projects/gamifying-forestry/), and [Blockalot](https://www.blockalot.de/), to a handfull of teachers and educators from all over France. It was also the occasion for the guests to meet irl again, and discuss how to better cooperate and contribute to the Minetest Edu ecosystem.

(the presentation was not recorded)

For more info, you can get in touch with them and other educators on [Discord](https://discord.gg/hUs9xT634S) and [Linkedin](https://www.linkedin.com/groups/7067035/).

**Comment by MisterE123** [comment]
Added, thank you!
