### ISSUE TITLE
[Content - May]: Education - Minestory Event

### ISSUE THREAD

**Issue by Lemente** [minetest/blog#110]
### Text:
The 31st of may the Minestory event was hosted in Terrasson-Lavilledieu in France.
Minestory is a project created in 2019 by Julien Crémoux, a teacher from France. Every year, hundreds of students from French schools across the world participate by replicating an heritage site from their area (like Notre-Dame de Paris, the medieval Louvre castle or the Besançon citadel) on a Minetest server, and then giving a virtual tour ingame.
The event was the occasion for some of the classes who are participating to this year edition to meet each other and present their project. The previous day the classes visited the Lascaux caves nearby.
Around 150 of the 413 students participating to this year edition of the project were present.

Thomate, Riwad and Lemente were invited to participate to the event:

They organised one of the 15 workshops proposed that day to the students (10 minutes sessions each).
A cave was built in Minetest and they used the [ggraffiti mod](https://content.minetest.net/packages/grorp/ggraffiti/) by [grorp](https://github.com/grorp) and grop's help to create a very simple [cave painting mod](https://github.com/Lemente/cave_painting) (contributions welcome!).
The students were challenged to draw one of the animal they saw the previous day. Since they were all already familiar with Minetest, most of them managed to draw something in the few minutes they had.

But more importantly, they got to meet the teachers and discuss with them about the problems they are facing, and ideas on how to facilitate the creation of Edu projects.
The teachers were passionnate and ready to try things out of their comfort zone (ex: 3d modeling) despite their lack of time.
Because of this lack of time, it is difficulty for them to develop skills, fix bugs, get help, develop long term solutions or share their own resources with others.
This highlights the importance of creating spaces for teachers to exchange about their implementation of Minetest in education and help each other, as well as the need to facilitate teachers access to technical help and guidance from members of the community.

### Main illustration:
![minestory_lascaux_photos](https://github.com/minetest/blog/assets/27686967/1e87256e-2087-4600-9b63-f6c4f27a736a)

### Other pictures
![IMG_20230601_011516](https://github.com/minetest/blog/assets/27686967/4b3d0a74-bb80-4886-9f51-52dfb156f125)
![firefox_OLcuLzOJU0](https://github.com/minetest/blog/assets/27686967/0e80ff77-6053-423b-81ee-f404bccebd5b)
![IMG_20230531_111014](https://github.com/minetest/blog/assets/27686967/58edc3cf-38f4-456c-8455-9e5b9654b771)
![firefox_ak3uknEFLG](https://github.com/minetest/blog/assets/27686967/d3061571-dd76-4b46-a49e-7b330e56be4c)
![firefox_zHRy7siZwv](https://github.com/minetest/blog/assets/27686967/632ffa62-1e90-4e56-977c-581964b0e9de)

**Comment by Lemente** [comment]
don't hesitate to ask questions so I can improve this submission!

**Comment by Lemente** [comment]
Thanks for the questions!


> Did they only make a cave painting mod in the two days?

The painting mod was made beforehand.
The first day we visited the Lascaux cave/Museum.
The second day the 150 kids were split into groups of 10, and participated to most of the 15 activities proposed that day.
A few of them were on Minetest. Others were not on computer, but were usually related to things kids had made/studied using Minetest during the year.


>I want to know what Minestory is

Minestory is a school project started in 2019. Here is a short description I wrote for the MT Edu page :

`Since 2019, more than 600 primary school students from 30 classes in 3 different countries have replicated heritage sites (like Notre-Dame de Paris, the medieval Louvre castle or the Besançon citadel), placed them on an interactive timeline and gave tours and presentations in the virtual world.`

Each class focuses on a local building, visit it irl and measure it, then rebuild it. The kids can then give online tours of the building within Minetest.


> why did the people there choose minetest over Minecraft

I'll have to ask them that!



Don't hesitate to ask if you have more questions!

**Comment by Lemente** [comment]
I improved the text and added pictures.
The article could also include a link the the Minestory website (in French): http://minetest.wp.ac-dijon.fr/minestory-frise-immersive-de-sites-du-patrimoine-architectural/

**Comment by MisterE123** [comment]
I edited the post for content (there were some things which were not relevant to minetest) and for length (it was really too long for the monthly post.

Here's what I have in the draft so far:
```
The Minestory event was hosted in Terrasson-Lavilledieu in France on May 31st.
Minestory was created in 2019 by Julien Crémoux, a teacher from France. Every year, hundreds of students from schools in France and from across the world replicate a heritage site from their area such as Notre-Dame in Paris or the Louvre castle on a Minetest server, and then give a virtual tour of their creation.
This year, 150 of the 413 participants visited the Lascaux caves nearby the town, which are known for their prehistoric cave paintings. The next day, Thomate, Riwad and Lemente organised a 10-minute workshop (one of 14 other workshops) in which a minetest cave was decorated using the ggraffiti mod to create simple cave paintings. The students were challenged to draw one of the animals they saw depicted the previous day. The event was also an opportunity for students to express their frustrations and ideas regarding edu projects.
```

**Comment by Lemente** [comment]
Thanks a lot!

I realize my original article was unclear, sorry: we were the ones who discussed with the teachers, not the students.
Here is a fix:

> Thomate, Riwad and Lemente were present to discuss the future possibilities of Minetest as an Edu ecosystem, and how to facilitate its adoption by educators. The next day, they organised a 10-minute workshop [...]


Can we also change "simple cave paintings" to "pixel-art cave paintings"? or does that sound weird?
