### ISSUE TITLE
[Content]: Mail mod huge improvements

### ISSUE THREAD

**Issue by Athozus** [minetest/blog#111]
### Blog Section

Mods News

#### Draft

On your server, you probably already used the `/mail` command or the button in the `unified_inventory`. You've been waiting for features and bug fixes. That's now ongoing !

Since the beginning of the year, we developed a lot of new features and fix many things (bugs, lags, ...). We've also included many translations : French, German, Modern/Traditional Chinese, Hungarian, Spanish, Brazilian Portuguese and maybe more ;). Our biggest new feature might be the sent messages folder, which required a whole rewriting of the storage system, thanks a lot to @BuckarooBanzay for that.

To tell a bit about the features we introduced, we've worked on mailing lists, sorters and filters, drafts, multiple selection, and we've reworked the about page also.

By the way, it is now possible to update it from [ContentDB](https://content.minetest.net/packages/mt-mods/mail/) !

While we're currently working on 1.2.0 release, which will bring settings, trash system, and big lag fixes notably, you're free to open an issue for any bug, request, etc., or a merge request for adding new translations, new features, a bug fix...

Finally, I would like to thanks a lot @S-S-X, @BuckarooBanzay and @fluxionary for the big help they gave to me, and also Your Land server, their players and their admins @Bastrabun and Ineva to bring me lot of new issues to fix, ideas, etc.

Hope you'll like the mail upgrades ;)

#### Comments on the above one

- I'm wondering if it is too promotional
- Maybe the last part for thx is unnecessary, I just wanted to thx them.
- At all, not sure it is well written.

### Add relevant details

Source code : https://github.com/mt-mods/mail
Initial author : Cheapie (creator), Rubenwardy (huge works)
ContentDB : https://content.minetest.net/packages/mt-mods/mail/

Quick screenshot below

![screenshot_20230614_200721](https://github.com/minetest/blog/assets/75171564/dc7aa164-8328-442f-a981-5bb17febd4a7)

**Comment by Athozus** [comment]
@MisterE123 small problem, as reported by @BuckarooBanzai some credits might be missing... :D But it's not a problem for me to be not credited, maybe Bucka's main problem ;)

**Comment by BuckarooBanzay** [comment]
@Athozus i don't have any problems with the blog-post but you could have added a bit more attribution to yourself, just look at the recent commit history and count your name https://github.com/mt-mods/mail/commits/master :wink:
