### ISSUE TITLE
Links/images should target _blank

### ISSUE THREAD

**Issue by GreenXenith** [minetest/blog#116]
(Taking the reader completely away from the focus is usually a bad idea.)

**Comment by erlehmann** [comment]
Middle click (to open in new tab) and back button exist though.

**Comment by GreenXenith** [comment]
That is not a reason to not use _blank.

**Comment by rubenwardy** [comment]
See https://css-tricks.com/use-target_blank/

I only use _blank when clicking the link could lose information. So it's good for a form where you're linking to help documentation. Not a fan of it on articles

**Comment by GreenXenith** [comment]
> See https://css-tricks.com/use-target_blank/

I'm glad he has an opinion, but what an obnoxious article. 

> Other sites should have normal-style links, but our site is special. Our site is more important and should never be left behind.

What a narrow-minded take, just because one site wants to use _blank doesn't mean other sites shouldn't. 

Also bold to assume every user even knows about middle-click to open or can be bothered to right click to open in a new tab.

https://stackoverflow.com/questions/3906898/to-target-blank-or-not-to-target-blank-that-is-the-question

If the opinions against outweigh mine, that is fine but this is just a matter of opinions.
