### ISSUE TITLE
[Content]: Famous Minecraft player making videos of minetest 

### ISSUE THREAD

**Issue by thunder1035** [minetest/blog#119]
### Blog Section

In Other News

### Please enter your content.

[Mumbo Jumbo](https://www.youtube.com/@ThatMumboJumbo) a
 Famous Minecraft player with 9.09M subscribers on YouTube had made a video of minetest
In which he plays in survival for a while and then introduces to Mesecon

### Add relevant details

his video is on youtube[https://youtu.be/va-YHeytvFQ](url)

**Comment by MisterE123** [comment]
Sorry, that video was not well-researched and, while it is useful to us regarding players' first impressions, it is not useful to new players because it does not present minetest as the content platform and engine that it is. We don't need to promote that, we are not desperate.
