### ISSUE TITLE
[Content]: Making Minetest an IOT device

### ISSUE THREAD

**Issue by 56independent** [minetest/blog#127]
### Blog Section

Mods News

### Please enter your content.

The brand-new [HTTPBlocks](https://content.minetest.net/packages/56independent/httpblock/) mod is now available. This mod allows POST and GET requests to be sent directly from Minetest. Since it connects to digilines, massively complicated systems can be constructed. Not only can one request a plaintext file from an endpoint, websites which record industry information can also be constructed.

Being a mod which uses the Minetest HTTP API, one must add this mod as a trusted mod to be able to use any of the features.

For the future, there are planned to implement HTML querying using a selector block as well as JSON to Lua Table converter blocks, which may be useful outside the HTTP environment.

Websockets, however, may not be implemented for a long time due to Minetest API limitations. This does limit the potential of the mod.

Stay tuned because 56independent, the creator of the mod, is hoping to make more mods that use digilines, including one which adds LISP to Minetest. This may take a long time to be released.

### Add relevant details

* Mod (you can use the screenshots; they're in HD):
    * https://content.minetest.net/packages/56independent/httpblock/

**Comment by GreenXenith** [comment]
Thank you for your submission! [August/September blog post](https://blog.minetest.net/2023/10/17/AugustSeptember/) is now published (68d2055).
