### ISSUE TITLE
[Content]: CTF's 10th anniversary

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#128]
### Blog Section

Games News

### Please enter your content.

August 16 was Capture the Flag's 10th anniversary. Capture The Flag is a multiplayer game where two teams of players battle to claim the other team’s flag whilst defending their own. Capture The Flag is played in a destructible voxel environment, allowing players to build defences and place traps.

For more information on CTF's history and development, see [the 10th anniversary blog post](https://blog.rubenwardy.com/2023/08/16/minetest-ctf-is-10/)

The 8th anniversary of the server will be the 1st of September. Fancy celebrating? From today until the 1st of September, there will be fireworks and party hats on the server  (`ctf.rubenwardy.com:30001`)

**Comment by GreenXenith** [comment]
Thank you for your submission! [August/September blog post](https://blog.minetest.net/2023/10/17/AugustSeptember/) is now published (68d2055).
