### ISSUE TITLE
[Content]: TypeScript For Minetest

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/blog#134]
### Blog Section

Mod Language News

### Please enter your content.

I have translated my project into TS with a full hand crafted TS typing system via declaration file specifically tailored for MT. This is heavily WIP and will be patched/upgraded/fixed as I work with it.

Everything you see below was written in TS with the TypeScriptToLua compiler.

![screenshot_20231114_182928](https://github.com/minetest/blog/assets/1088750/03f00b69-6a1a-4d0c-822b-0293bfd77a88)

### Add relevant details

TypeScriptToLua: https://typescripttolua.github.io/
Project: https://github.com/jordan4ibanez/forgotten-lands

**Comment by MisterE123** [comment]
I looked through the forgottenlands code, and I don't see licensing on the textures, so I'm a bit wary of including the screenshot.
