### ISSUE TITLE
Post about the winner of the game Jam

### ISSUE THREAD

**Issue by TheShadowOfHassen** [minetest/blog#141]
Was there any plan to have a post covering the entrants to the latest game jam?

**Comment by MisterE123** [comment]
That will appear in the next post, yes. Hopefully released next week or sooner.

**Comment by TheShadowOfHassen** [comment]
Cool. I'll close this issue and when a PR is opened I'll help look it over (the more eyes we have on it the quicker it can be merged!)

**Comment by MisterE123** [comment]
https://github.com/minetest/blog/pull/142
