### ISSUE TITLE
Add official translations

### ISSUE THREAD

**Issue by appgurueu** [minetest/blog#17]
See e.g. https://forum.minetest.net/viewtopic.php?p=411067#p411067.

**Comment by Miniontoby** [comment]
I can help translating to Dutch, but I will have to see if I can get enough time to do it

**Comment by rubenwardy** [comment]
If this is done, then it'll be very important that translations don't block the release of the English article

**Comment by Lemente** [comment]
How would this work technically?
Could it be done through a common tool, like weblate?

Or is the process different for larger texts?

**Comment by Zughy** [comment]
As much as I care about accessibility, this is simply not doable at the moment. There are basically two people behind the blog, and one of them is a core dev already involved in many other aspects (modding book, CDB, engine, social networks, Discord). They can barely deliver a piece per month, I think trying to implement such a thing would be cruel - we need more official writers!
