### ISSUE TITLE
[Content] Updates to Traitor (Among Us knockoff)

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/blog#19]
Traitor has recently received two long requested features, vents and level sabotage. The vents have been adapted from Joe7575's hyperloop mod and allow for traitors and ghosts to instantly travel from vent to vent on levels, if the level builders add them of course. This feature has been requested for over a year. Level sabotage, while slightly buggy, is available. Currently there is only one node that can be sabotaged by the traitor, the switch. Level designers can choose how long the players have to repair the sabotaged node, and if repairing, or failing to repair, the node should result in the match ending.
Traitor is running on the 'In Our Midst' server where there is currently work being done on an academy which further explains game mechanics for players and builders.

![post](https://user-images.githubusercontent.com/8930456/175827886-96c2f73e-f305-4b00-ad4f-c42e21fb7edd.png)
(Pictured: Switch that can be sabotaged, and an access point to the vent system)

**Comment by GreenDirkfried** [comment]
And there are already levels on the 'In Our Midst' server that include those new features :-)
Grab some friends and try a game there!

**Comment by MisterE123** [comment]
The announcement relating to the server was included in the servers section @GreenDirkfried. Thank you both for your submission!
