### ISSUE TITLE
[Content] Camera API article

### ISSUE THREAD

**Issue by kilbith** [minetest/blog#21]
By request of @MisterE123 

« There is currently one camera per player, this Camera API allows to use more (static) cameras into the game at different places. They can be used for cutscenes, screen casting onto an entity (HL² Dr Breen speech like), security cameras, vehicle's rear views, etc. »

Demo: https://www.youtube.com/watch?v=jrxcztUFLjc

**Comment by MisterE123** [comment]
Thank you for your submission! its included in the June post; closing.
