### ISSUE TITLE
[content] Minetest workshops for teachers at the exploreandlearn online conference

### ISSUE THREAD

**Issue by chrbinder** [minetest/blog#29]
From July 3 to July 6, 2022, online workshops on Minetest, Game-based Learning, coding and robotics were held during the [exploreandlearn@LMZ](mailto:exploreandlearn@LMZ) event. Teachers and others interested in education could participate in workshops and presentations from the three categories ‘playandlearn’, ‘buildandlearn’, and ‘codeandlearn’.

![exploreandlearn_logo](https://user-images.githubusercontent.com/47057923/182182153-3dd2c1f3-1118-4bd1-8fb3-3e2710cd3d3d.jpg)
exploreandlearn@LMZ logo by Landesmedienzentrum Baden-Württemberg, Germany

On Tuesday, July 5, there was a one-day workshop concerned with future-oriented learning and how to develop learning scenarios for educational contexts. The workshop was held by Chris Binder and Tammo Engelhard, who are both freelance trainers for the [Landesmedienzentrum Baden-Württemberg](https://www.lmz-bw.de/), Germany (LMZ BW). In the workshop, teachers were introduced to Minetest and its potentials for learning. Starting from some gameplay examples, the participants developed learning scenarios in small groups and later on, built prototypes of their ideas.

![eal_01](https://user-images.githubusercontent.com/47057923/182182202-aaec63ae-edfd-44af-bea1-3d878601fe7a.png)
workshop screenshot by chbinder

On Thursday, July 7, two shorter workshops were held to introduce a map template that can be used by teachers in conjunction with the [BLOCKALOT](https://blockalot.de/) web dashboard for Minetest servers.
The swampy landscape offers different points of interest that each pose their own challenges to the learners. These POI can be modified by teachers to cater to their curricula or intended learning outcomes. However, it is crucial that learners remain active and not just passive recipients of knowledge. One point of interest is an area with floating islands and an old house that needs to be renovated with sustainability in mind. 
Then, the learners choose sustainable development goals themselves and build the settlement according to their own plans. The whole group can discuss and evaluate the results after the building phase.
The players are provided with useful materials in a cave, where they may also write ideas about sustainable building on the walls.

![eal_02](https://user-images.githubusercontent.com/47057923/182182223-0cae669f-935c-47c8-98f9-c57ec93654bf.png)
workshop screenshot by chbinder

The BLOCKALOT team is currently in the process of translating its BLOCKALOT dashboard and [companion wiki](https://wiki.blockalot.de/) into English. Take a look at [www.blockalot.de](http://www.blockalot.de/) if you are interested in how to use Minetest for future-oriented learning! If you need assistance, the BLOCKALOT team is happy to help with any questions in English, French, and German.

**Comment by rubenwardy** [comment]
Do you have any pictures of the actual event, in real life? Or was it mostly virtual
