### ISSUE TITLE
Document how to contribute (_github/CONTRIBUTING.md)

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#4]

**Comment by MisterE123** [comment]
Ideally, there should be options to use: issue tracker, a gitlab mirror issue tracker, email, and forums.

**Comment by rubenwardy** [comment]
> Ideally, there should be options to use: issue tracker, a gitlab mirror issue tracker, email, and forums.

I've created a GitLab mirror, only thing remaining is an email address

**Comment by MisterE123** [comment]
mistere123.coding@gmail.com for now
