### ISSUE TITLE
[Content: Oct] Urban planning workshop with Minetest

### ISSUE THREAD

**Issue by Lemente** [minetest/blog#43]
On October 25, 26 and 27, Lemente and Thomate organised a workshop with Minetest for the city of Maubeuge in France.
Each day, a group of young citizens, between 10 and 16 years old, shared ideas to improve the public space in their neighborhood, and then built these ideas in an ingame map of their city.

This gave the opportunity to urban planners to see what young people wanted for their local area, and discuss current issues with them.

![minetest_workshop_maubeuge_2022_lemente_thomate](https://user-images.githubusercontent.com/27686967/200001049-80284692-0410-4654-837b-ebadfd883c9e.png)
(photos and screenshots by Lemente and Thomate)
on the left: some of the areas built by participants
on the bottom right: Fabien (director of the urban planning agency) with Julien (in charge of the urban renewal project for the city) and Thomas (one of the workshop organizer/animator) discussing the project

**Comment by MisterE123** [comment]
added to wip post
