### ISSUE TITLE
[Content: Nov] Advtrains Supplemental organisation announcement

### ISSUE THREAD

**Issue by W3RQ01** [minetest/blog#44]
On the 9th of november the Advtrains Supplemental organisation has been publicy announced on the forums [https://forum.minetest.net/viewtopic.php?t=14726&p=417675](forums), all the advtrains related mods are going to be hosted/migrated/mirrored there. Current leaders are W3RQ01, Blockhead and Orwell96. The organisation is on notabug [https://notabug.org/advtrains_supplemental](notabug).

**Comment by y5nw** [comment]
> On the 9th of november the Advtrains Supplemental organisation has been publicy announced on the [forums](https://forum.minetest.net/viewtopic.php?t=14726&p=417675), all the advtrains related mods are going to be hosted/migrated/mirrored there. Current leaders are W3RQ01, Blockhead and Orwell96. The organisation is on [notabug](https://notabug.org/advtrains_supplemental).

Not sure about the significance, but to add some context: previously Advtrains-related resources have been all over the place, and, in particular, some of the wagons from mbb have not been updated for quite a while. The Advtrains Supplemental organization was set up to mirror some Advtrains-related mods and to maintain ones without much activity, especially after [mbb gave permission regarding copyright](https://forum.minetest.net/viewtopic.php?f=11&t=14726&p=410183#p410183) and [the Advtrains organization was set up](https://notabug.org/advtrains) to mirror the repos on bananach.space.

**Comment by rubenwardy** [comment]
I don't think that creating a Git organisation is notable enough to be in the blog. Is there any new content you can show off? What might interest someone who might not use advtrains?

**Comment by y5nw** [comment]
From my knowledge this is mainly related to organization rather than (currently) adding new content. IMO this is likely more appropriate for the Advtrains wiki instead.

**Comment by MisterE123** [comment]
I will simply make a note in the "In other News" section, that this is where you can find a bunch of adv trains stuff all collected.

**Comment by MisterE123** [comment]
added in https://github.com/minetest/blog/pull/49
