### ISSUE TITLE
[Content] Definition Ripper Mod Released

### ISSUE THREAD

**Issue by Warr1024** [minetest/blog#50]
> Include who is working on the project.

Warr1024 (author of NodeCore and Klots)

> Include a brief description. Keep it short. Links to further details are encouraged.

Minetest Definition Ripper was developed as part of the development process of Klots, for the Game Jam, and publicly released in late November.

It's a tool for more efficient game development, using existing community art assets (node definitions, textures, and media) without including problematic behavior or other game logic in new games.  It also helps prune unused assets, which can shrink download sizes, improve load times, and reduce memory usage.

See the ContentDB description for more details:

https://content.minetest.net/packages/Warr1024/defripper/

This tool was used to maintain the "scenery" building node definitions for Klots, enabling the developer to focus on gameplay mechanics, level building, and overall design, without going through the tedium of recreating all the basic terrain nodes from scratch yet again.

> Screenshots

Probably the best currently-available screenshots to use for this might be the ones from Klots, which show example "ripped" node definitions used in an actual game.  https://content.minetest.net/uploads/706c4d1a07.jpg in particular shows a lot of MTG and scifi_nodes textures reused in Klots, which was done almost entirely through this tool.  All screenshots for Klots were taken by Warr1024.

**Comment by MisterE123** [comment]
https://github.com/minetest/blog/pull/49

Thank you!
