### ISSUE TITLE
Additional context for Minetest art projects

### ISSUE THREAD

**Issue by MrRar** [minetest/blog#51]
I think the blog posts should include additional context for Minetest art projects. Right now they just include a screenshot, the name of the work and the name of the author. This leaves me with some questions. Is the world available for downlaod? Was it made on a creative server? If so which and what are the coordinates? Or is this just something that someone made in a single player game and shared a screenshot? If so where is the original post where the screenshot was shared?

**Comment by MisterE123** [comment]
Unless otherwise mentioned, the world will not be available for download. 
If the build was on a server, it would ideally indicate that. Coordinates do not seem appropriate for the blog. 
Usually it will come from singleplayer.

**Comment by MisterE123** [comment]
Well, I appreciate the feedback, and we have noted it. When appropriate, I will attempt to include relevant information in the captions.

Closing.
