### ISSUE TITLE
[content] randungeon (dungeon generator mod anncement)

### ISSUE THREAD

**Issue by phseiff** [minetest/blog#53]
> who is working on the project.

me ([Phii](https://content.minetest.net/users/Phii/))

> Include a brief description. Keep it short. Links to further details are encouraged

I wrote a procedual dungeon generator in minetest for complex highly randomized big dungeons, with treasure rooms and forest caves and randomized materials, using almost exclusively the blocks provided my minetest game. I think out of all the mods that tried themselves at tile-based dungeon generation so far this one pushes the limits the most, as far as i can tell.

ContentDB Link: https://content.minetest.net/packages/Phii/randungeon/
full documentation on GitHub: https://github.com/phseiff/randungeon

> Include a screenshot and who took it

screenshot:

![screenshot](https://content.minetest.net/uploads/c15976c912.png)

(screenshot taken by me)

> Additional Notes

I hope I understood correctly that it's okay/appreciated to submit ones own mods as a content suggestion for the blog posts?

I released the mod some days ago this january so i'm sharing it in case this mod meets your requirements for being good/big/contentfull enough to be included in the january blog post (it certainly meets the last two requirements, i think).

**Comment by MisterE123** [comment]
Added, thanks!
