### ISSUE TITLE
[mod news] OTP

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/blog#57]
# Raw markdown

```markdown
[OTP](https://content.minetest.net/packages/mt-mods/otp/) is a mod by [BuckarooBanzai](https://content.minetest.net/users/BuckarooBanzay/) published under the [mt-mods](https://content.minetest.net/users/mt-mods/) umbrella.
It allows security-aware players to use a second factor to protect their accounts.
```

# Rendered

[OTP](https://content.minetest.net/packages/mt-mods/otp/) is a mod by [BuckarooBanzai](https://content.minetest.net/users/BuckarooBanzay/) published under the [mt-mods](https://content.minetest.net/users/mt-mods/) umbrella. It allows security-aware players to use a second factor to protect their accounts.

# Links

Git: https://github.com/mt-mods/otp/
ContentDB: https://content.minetest.net/packages/mt-mods/otp/

# Screenshots

OTP Setup
![screenshot2](https://user-images.githubusercontent.com/39065740/215334353-753d2d1e-8541-4c3d-bd9c-7574d82872ef.png)

OTP verification
![screenshot1](https://user-images.githubusercontent.com/39065740/215334798-b41dbaff-f04f-47a7-ac0a-6a8c54991c9e.png)

**Comment by MisterE123** [comment]
Added, thanks!
