### ISSUE TITLE
Blockexchange upgrades

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/blog#58]
# Raw markdown

```
[Blockexchange](https://blockexchange.minetest.ch/) got a few new features, including the possibility to update the uploaded
schematics incrementally, that means larger builds can be updated in smaller parts without uploading the whole build again.
```

# Rendered

[Blockexchange](https://blockexchange.minetest.ch/) got a few new features, including the possibility to update the uploaded
schematics incrementally, that means larger builds can be updated in smaller parts without uploading the whole build again.

# Links

* Main page: https://blockexchange.minetest.ch
* Github: https://github.com/blockexchange

# Screenshots

![Screenshot_2023-01-29_15-50-47](https://user-images.githubusercontent.com/39065740/215334537-e916f197-ee7e-49dc-b6be-f876c2e48ecd.png)

**Comment by MisterE123** [comment]
Added, thanks!
