### ISSUE TITLE
[content] Piranesi Restoration Project

### ISSUE THREAD

**Issue by Warr1024** [minetest/blog#59]
- For people interested in Piranesi from the jam, but who found crashes and bugs made it impossible to complete, give this game a try.
- Aims to recreate the puzzles in Piranesi as originally intended, but with bugfixes, refinements, quality-of-life improvements, improved accessibility, and translations.  More highlights of improvements in the CDB description.
- iarbat does not intend to continue the original Piranesi now, and endorses Piranesi Restoration Project as its successor.
- Good screenshots on CDB.  My favorite is probably the [Clock Room](https://content.minetest.net/uploads/0679d5f6d3.jpg) one, since that room wasn't even accessible in the official jam edition of the game.

---

- ContentDB: https://content.minetest.net/packages/Warr1024/piranesi_redo/
- Source: https://gitlab.com/sztest/piranesi_redo
- Issue Tracker: https://gitlab.com/sztest/piranesi_redo/-/issues
- Weblate: https://hosted.weblate.org/projects/minetest/game-piranesi-redo/

**Comment by MisterE123** [comment]
@Warr1024 Thank you!, added. 

Also, in the future, please write as a description rather than a bullet point list; then I can copy and edit it much easier. 
Unless you don't have time; I'd rather have it like this than have nothing.
