### ISSUE TITLE
[content] Asuna is now available on ContentDB

### ISSUE THREAD

**Issue by EmptyStar** [minetest/blog#67]
### Who is working on the project?

[EmptyStar](https://content.minetest.net/users/EmptyStar/)

### Description

[Asuna](https://content.minetest.net/packages/EmptyStar/asuna/) is a new work-in-progress game that brings together some of the very best biome and world decoration mods that the Minetest community has to offer. Journey through a potpourri of natural wonders as you traverse beautiful and breathtaking landscapes. Forests, meadows, jungles, tundras, deserts, swamps, and more await you at every horizon.

### Screenshots

Screenshot of Asuna's main menu by EmptyStar:

![image](https://user-images.githubusercontent.com/11603556/215882074-63970bcd-1595-47e1-8c60-220bf10850fb.png)

**Comment by MisterE123** [comment]
Added, thank you!

I used ingame screenshots from CDB though.
