### ISSUE TITLE
[content] opening of an unofficial Minetest Edu discord server

### ISSUE THREAD

**Issue by Lemente** [minetest/blog#68]
Would this be enough? Should I add more details?

> You can now join a Discord server dedicated to the usage of Minetest for Education, Workshops, and more!
> It is a place made to discussing existing projects, sharing resources and helping each other.
> 
> https://discord.gg/hUs9xT634S

we could add this?

> There are many people trying to use Minetest for all kinds of purposes, but sadly their projects often stay at the state of prototypes. Starting a Minetest project requires a specific set of skills, like creating a game, hosting a server, setting moderation tools within the game, developing custom mods, ...
> For teachers, educators and workshop facilitators, this can be a complicated and time consuming task.
> 
> The goal of this discord server is to bring together anyone interested in using Minetest as a virtual tool, whether it is for education, artistic or creative workshops, citizen participation in urban planning, or any other use you might think of.
> 
> This will allow us to learn from existing projects, share specific resources we have produced that might be useful to others, and create new ones together.

**Comment by MisterE123** [comment]
Added, thank you!
