### ISSUE TITLE
Use an issue form/template for the blog submission

### ISSUE THREAD

**Issue by Panquesito7** [minetest/blog#73]
### Description

If we add an issue form/template for submitting blogs, it'll make it much easier to contribute to new blog posts and know exactly what information is needed, and even have required fields which the users must answer.

What do you think about this? Thanks. 🙂

**Comment by MisterE123** [comment]
I like the idea, but I need @rubenwardy to implement it since I do not have permissions to as of last time I checked.

**Comment by rubenwardy** [comment]
I'd suggest a template rather than a form, it's creative and shouldn't be prescriptive

**Comment by Panquesito7** [comment]
Both templates or forms would work well.
A form would be better, IMO, but choose whatever you think is best. 🙂

**Comment by MisterE123** [comment]
Thank you for the suggestion. It is done.
