### ISSUE TITLE
[Post] 5.7.0 release

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#75]
We'll need lots of screenshots to demonstrate new features. Ideally freely licensed so the press can reuse them. Should include bloom, shadows, and long view range.

Notes:

* Jude Melton-Houghton
* Graphics
	* New graphical effects: postprocessing shaders, bloom, and dynamic exposure
    * Improved performance on high-end systems at large view ranges (some report 60FPS at 1000 nodes view range)
    * Improved mapblock meshgen performance (will result in faster map loading)
    * Dynamic shadow improvements
* Lots of other performance improvements
* Rotating entity selection boxes
* Android: support for using a fixed crosshair, like on desktop
* Mods can now find out the player's window size, which will allow for full-screen and more responsive GUIs
* Deprecations
	* It's no longer possible to load a world if mods have unsatisfied dependencies. Before, Minetest would automatically disable these mods - but it led to confusion. You will need to add the missing dependency or disable the mods

**Comment by rubenwardy** [comment]
Nice image, asked for permission

[![image](https://forum.minetest.net/download/file.php?id=27351)](https://forum.minetest.net/viewtopic.php?p=422183#p422183)

**Comment by MisterE123** [comment]
Submitted by kilbith:
![image](https://user-images.githubusercontent.com/61124264/223836870-27f97f48-c8af-475e-8e0d-253382765725.png)
![image](https://user-images.githubusercontent.com/61124264/223837078-741e89f7-81ea-4bff-8d8b-515035566f7a.png)
