### ISSUE TITLE
[Content] Engine news for February

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#76]
completed

* https://github.com/minetest/minetest/pull/12367
* [load distance optimisations](https://github.com/minetest/minetest/pull/13133)
* Ability to set sky tilt on server (not sure if notable enough?) https://github.com/minetest/minetest/pull/13193
* https://github.com/minetest/minetest/pull/13189

ongoing

* Preparing for 5.7.0 release
* https://github.com/minetest/minetest/pull/13253 
* https://github.com/minetest/minetest/pull/13234 (notable?)

**Comment by MisterE123** [comment]
Added to the February post, please close when you are satisfied with it.
