### ISSUE TITLE
[Content] Repixture 3.8.0 - boats

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#77]
https://forum.minetest.net/viewtopic.php?p=421822#p421822

![](https://cdn.fosstodon.org/media_attachments/files/109/835/789/244/763/841/original/89774e5d07cb70ac.png)

![boat](https://i.imgur.com/sXLQ741.png)

**Comment by MisterE123** [comment]
Added in https://github.com/minetest/blog/pull/80/commits/b844455a0513b3377061a1d7b60b776ea04c8710
