### ISSUE TITLE
[Content] New stuff on ContentDB

### ISSUE THREAD

**Issue by rubenwardy** [minetest/blog#78]
Feel free to curate these

* Minesweeper 3d: https://content.minetest.net/packages/Hume2/minesweeper_3d/
* Offhand items: https://content.minetest.net/packages/TestificateMods/offhand/

**Comment by MisterE123** [comment]
Added in https://github.com/minetest/blog/pull/80/commits/fe3c264f6ba870fdba66945f04150b0c0ec09d63
