### ISSUE TITLE
[Content] AP Airship mod

### ISSUE THREAD

**Issue by APercy** [minetest/blog#81]
https://github.com/APercy/ap_airship

This mod is an experiment with attachments and some other ideas I'm testing. It's derived from Steampunk Blimp, but with some special features like clickable seats, control, ladder, etc. The fuel is disabled at this moment, so it can fly forever, but in future I'll think something to make it interesting. And it is affected by winds, including the climate_api from TestificateMods.

The current walk_map.lua used on it is an evolution from the first walk mechanism and in future I want to make it a library mod

**Comment by MisterE123** [comment]
Thanks for this. Could you add one or two compelling screenshots as well?

**Comment by APercy** [comment]
How I could do it?

**Comment by MisterE123** [comment]
https://media.discordapp.net/attachments/940383257147629608/1084566232646303906/screenshot_20230312_164622.png?width=717
https://media.discordapp.net/attachments/940383257147629608/1084566232965074944/screenshot_20230312_164632.png?width=717&height=425&height=425
https://media.discordapp.net/attachments/940383257147629608/1084566233262850088/screenshot_20230312_164650.png?width=717&height=425
https://media.discordapp.net/attachments/940383257147629608/1084566233548079205/screenshot_20230312_164701.png?width=717&height=425
https://media.discordapp.net/attachments/940383257147629608/1084566233833296013/screenshot_20230312_164917.png?width=717&height=425

**Comment by MisterE123** [comment]
![screenshot_20230312_164632](https://user-images.githubusercontent.com/61124264/224570866-322ed0f8-20d5-4d68-97da-9e2e3271e541.png)
![screenshot_20230312_164650](https://user-images.githubusercontent.com/61124264/224570876-8c3fea3f-faf4-4e88-a570-d3c00f8da917.png)
![screenshot_20230312_164701](https://user-images.githubusercontent.com/61124264/224570884-268234a3-f61b-44f3-b671-55bfbf214036.png)
![screenshot_20230312_164917](https://user-images.githubusercontent.com/61124264/224570886-ac690f9f-394e-458b-9e64-d25032dd8435.png)
![screenshot_20230312_165242](https://user-images.githubusercontent.com/61124264/224570896-dc13231f-bd7f-41b6-86c2-959d272acfcf.png)
![screenshot_20230312_164622](https://user-images.githubusercontent.com/61124264/224570904-e101692d-bbd4-4429-8591-c6b7d1aa09a0.png)

**Comment by MisterE123** [comment]
Just drag and drop in the textbox (I know I told you on discord but this is for the benefit of others who read this)

**Comment by MisterE123** [comment]
Added, thank you!
