### ISSUE TITLE
[Content]: End Portal Buckets for MineClone 2

### ISSUE THREAD

**Issue by PrairieAstronomer** [minetest/blog#88]
### Blog Section

Mods News

### Please enter your content.

Recently released new mod for MineClone2...the end portal buckets. This mod adds an easy way to access the end from anywhere by carrying an placeable end portal in a bucket. Thank you to FossFanatic for creating the texture.

### Add relavant details

![image](https://user-images.githubusercontent.com/61390218/224574650-f7ca76ed-374c-43fa-859f-f8ae3dcc62a4.png)
Using the end portal bucket. (PrairieWind)

https://content.minetest.net/packages/PrairieWind/mcl_end_portal_bucket/
https://forum.minetest.net/viewtopic.php?p=422449#p422449

**Comment by MisterE123** [comment]
Can you get a high-resolution screenshot?

**Comment by MisterE123** [comment]
Since this mod is somewhat hacky, and the changes requested were not made, Not adding. 

Feel free to present this mod in a future post if it gets updated to be presentable, and if there is a high-resolution screenshot.
