### ISSUE TITLE
[Content]: Pizzaria

### ISSUE THREAD

**Issue by Extex101** [minetest/blog#91]
### Blog Section

Mods News

### Pizzaria
I just released my Pizzaria mod

Due to Minetest Game's inherent lack of Meat, Cheese, Tomatoes, Olives
I've added a special item, The Mese mutation Crystal to gain the necessary items, making it a pretty end-game food source.
A steady stream of mese, gold, and apples are required to keep your pizza making in business.

I have provided support for some other mods, pineapple, mobs mods for meat ect.

But if there's no fallback for meat, that's when the mutation crystal can be used to mutate player bones into meat.
Could be interesting having head-hunters killing people to get meat for their pizzas.

The mod makes the player very involved in the pizza making process, e.g. Punch dough with rolling pin, placing the ingredients on your pizza, physically placing your pizza into the pizza oven, and finally cutting it up with your pizza cutter.
![876a839910](https://user-images.githubusercontent.com/33675971/224859397-2ec6fc21-0fb9-45d5-9925-07d5d58dff19.png)
![Screenshot_20230313-164342_(1)-01](https://user-images.githubusercontent.com/33675971/224859461-05752733-b180-42eb-b02d-38469e928989.jpeg)

### Add relavant details

https://forum.minetest.net/viewtopic.php?t=29270

https://content.minetest.net/packages/Extex/jelys_pizzaria/

**Comment by MisterE123** [comment]
thank you, the content submission looks good

**Comment by MisterE123** [comment]
Added, thanks!
