### ISSUE TITLE
[Content]: Mobs Redo Update

### ISSUE THREAD

**Issue by tenplus1** [minetest/blog#93]
### Blog Section

Mods News

### Please enter your content.

Mobs Redo API has just added a requested feature that highlights a mob when punched.  This can be enabled in settings by toggling 'mob_hit_effect' to true having mobs glow a healthy orange colour, or using whatever 'damage_texture_modifier' is set to in the mob definition.  Punched mobs can also play an 'injured' animation if it's set in the mob definition also.
![shot-2023-03-16_08-05-45](https://user-images.githubusercontent.com/8145060/225554315-ddf67f58-289a-47ed-862e-2cc8e5f02284.jpg)

**Comment by MisterE123** [comment]
Added, thank you!
