### ISSUE TITLE
[Content/March]: Everness deep ocean update

### ISSUE THREAD

**Issue by JurajVajdaCQL** [minetest/blog#94]
### Blog Section

Mods News

### Please enter your content.

Everness got "deep ocean" update. Adds 3 new ocean biomes with new sand and respective craft-able blocks, dozen of new corals a ocean plants, new "shell of underwater breathing" what makes your exploring these biomes longer without loosing your breath and underwater structures with loot chests. Additionally in this update were includes new sounds for dirt, grass and ice blocks and new Igloo house with loot chest what can be found in frosted icesheet biomes. Happy exploring.

### Add relavant details

https://content.minetest.net/packages/SaKeL/everness/

coral forest deep ocean: https://content.minetest.net/uploads/b2135b4eb1.png
crystal forest deep ocean: https://content.minetest.net/uploads/344a737bf5.png
cursed lands deep ocean: https://content.minetest.net/uploads/2e9b124bbb.png

**Comment by JurajVajda** [comment]
Update: Evernes is now MTG agnostic a compatible (technically) with any game. All new sounds and bunch of reworked textures are included.

**Comment by MisterE123** [comment]
Thank you, Added!
