### ISSUE TITLE
[Content]: X Farming Scarecrow

### ISSUE THREAD

**Issue by JurajVajda** [minetest/blog#95]
### Blog Section

Mods News

### Please enter your content.

X Farming added new scarecrow decoration for your farms. Scarecrow can be activated with (x farming) bonemeal what will activate the scarecrow resulting in faster crops growth. Activated scarecrow will grow flora/fauna around him by default but this can be used for faster farming crops growth as well.

### Add relavant details

mod: https://content.minetest.net/packages/SaKeL/x_farming/
scarecrow: https://content.minetest.net/uploads/30a47b669e.png
video: https://youtu.be/3Sz1EZxPMms

**Comment by MisterE123** [comment]
Thank you, added!
