### ISSUE TITLE
[Content/March]: Modlib has a working B3D to glTF converter

### ISSUE THREAD

**Issue by appgurueu** [minetest/blog#97]
### Blog Section

In Other News

### Content

After fixing the latest bug, modlib's B3D to glTF converter seems to handle all the B3Ds (about one thousand) I extracted from 2021 ContentDB well; a few invalid models are also rejected (e.g. some models contain an XXXX chunk or MESH chunks missing TRIS, lol).

All valid B3D models should work however (if they don't, that's a bug).

The merit of this is that it allows editing B3Ds even if the source Blender files have been lost. Alternative conversion processes seem to exist though (but probably aren't as reliable / lossless).

It may also help with providing an easy upgrade path from B3D to glTF if Minetest is to get support for it in the future.

### Add relevant details

Documentation for the B3D module, including an example for how to convert B3Ds to glTF: https://github.com/appgurueu/modlib/blob/master/doc/b3d.md

![Advanced trains wagon in Blender](https://user-images.githubusercontent.com/34514239/229354312-149e0dcf-88c3-46a9-87ac-55ae4abb8519.png)

(the screenshot doesn't convey it, but animations are fully supported)

**Comment by MisterE123** [comment]
Added, thank you!
