### ISSUE TITLE
[Content/April]: New easter egg mod

### ISSUE THREAD

**Issue by Ineva-A** [minetest/blog#98]
### Blog Section

Mods News

### Please enter your content.

In this new mod we will go back to our childhood! 
Go and search with your family or friends wild spawned eggs. 
You can eat some yummy chocolate while crafting!
![Screenshot (47)](https://user-images.githubusercontent.com/85231245/230169798-058ad3bb-2922-4c81-a132-9212782fda9c.png)

### Add relavant details

This mod is from Ineva 
with help from co-contributor:
sven
glubux

**Comment by MisterE123** [comment]
Added, thanks!
